In [66]:
import pandas as pd

In [67]:
df = pd.read_csv('./brasil-mineracao.csv')

In [68]:
df.head()

,WKT,PROCESSO,NUMERO,ANO,AREA_HA,ID,FASE,ULT_EVENTO,NOME,SUBS,USO,UF,DSProcesso
0,POINT (-43.7707663707609 -20.6393079010862),2004/1935,2004,1935,161.49,{E7C652AE-4A72-4E98-8F0D-47E4F50DA3DD},CONCESSÃO DE LAVRA,436 - CONC LAV/DOCUMENTO DIVERSO PROTOC EM 10/...,NEXUS MANGANES S.A.,MINÉRIO DE MANGANÊS,Demais substâncias,MG,002.004/1935
1,POINT (-46.8417232414918 -20.9479278898186),2125/1935,2125,1935,35.00,{6B5CCEF3-61C2-4966-87BB-C601F581D61C},CONCESSÃO DE LAVRA,418 - CONC LAV/RAL ANO BASE APRESENTADO EM 14/...,Organização Teixeira Mendes Ltda,ÁGUA MINERAL,Demais substâncias,MG,002.125/1935
2,POINT (-43.862178918326 -20.4229306108558),2952/1935,2952,1935,38.11,{E4F72B41-F05E-4F7B-AF96-789DCC05858F},CONCESSÃO DE LAVRA,418 - CONC LAV/RAL ANO BASE APRESENTADO EM 24/...,VALE S.A.,FERRO,Demais substâncias,MG,002.952/1935
3,POINT (-40.4731400627918 -11.2193638449948),4410/1935,4410,1935,405.00,{CB4A62EC-C067-47C4-A6FE-8331DD245FC1},CONCESSÃO DE LAVRA,477 - CONC LAV/RECURSO PROTOC EM 17/10/2024,MINERACAO VALE DO JACURICI S A,MANGANÊS,Demais substâncias,BA,004.410/1935
4,POINT (-42.1208439491585 -21.1024869907957),4779/1935,4779,1935,5.43,{677E75E5-1A37-441A-99EA-2DFFBAAE8246},CONCESSÃO DE LAVRA,418 - CONC LAV/RAL ANO BASE APRESENTADO EM 15/...,Empresa Hidromineral Fluminense Ltda-ME,ÁGUA MINERAL,Demais substâncias,RJ,004.779/1935

In [69]:
df_filtrado = df.drop(['PROCESSO', 'NUMERO', 'ID', 'ULT_EVENTO', 'DSProcesso', 'FASE'], axis=1)

In [70]:
df_filtrado = df_filtrado[df_filtrado['SUBS'] != 'DADO NÃO CADASTRADO']

In [71]:
df_filtrado.head()

,WKT,ANO,AREA_HA,NOME,SUBS,USO,UF
0,POINT (-43.7707663707609 -20.6393079010862),1935,161.49,NEXUS MANGANES S.A.,MINÉRIO DE MANGANÊS,Demais substâncias,MG
1,POINT (-46.8417232414918 -20.9479278898186),1935,35.00,Organização Teixeira Mendes Ltda,ÁGUA MINERAL,Demais substâncias,MG
2,POINT (-43.862178918326 -20.4229306108558),1935,38.11,VALE S.A.,FERRO,Demais substâncias,MG
3,POINT (-40.4731400627918 -11.2193638449948),1935,405.00,MINERACAO VALE DO JACURICI S A,MANGANÊS,Demais substâncias,BA
4,POINT (-42.1208439491585 -21.1024869907957),1935,5.43,Empresa Hidromineral Fluminense Ltda-ME,ÁGUA MINERAL,Demais substâncias,RJ

In [72]:
len(df_filtrado['SUBS'].unique())

325

In [54]:
substituicoes = {
    'OURO': ['MINÉRIO DE OURO', 'OURO NATIVO', 'OURO PIGMENTO', 'ALUVIÃO AURÍFERO', 'OURO'],
    'COBRE': ['MINÉRIO DE COBRE', 'COBRE'],
    'MANGANÊS': ['MINÉRIO DE MANGANÊS', 'MANGANÊS'],
    'ALUMÍNIO': ['MINÉRIO DE ALUMÍNIO', 'BAUXITA', 'GIBBSITA', 'HIDRARGILITA', 'BAUXITA FOSFOROSA'],
    'FERRO': ['MINÉRIO DE FERRO', 'HEMATITA', 'MAGNETITA', 'FERRO MANGANÊS', 'ITABIRITO'],
    'ZINCO': ['MINÉRIO DE ZINCO', 'ZINCO'],
    'NÍQUEL': ['MINÉRIO DE NÍQUEL', 'SILICATOS DE NÍQUEL', 'NÍQUEL'],
    'CHUMBO': ['MINÉRIO DE CHUMBO', 'SULFETOS DE CHUMBO', 'GALENA', 'CHUMBO'],
    'ESTANHO': ['MINÉRIO DE ESTANHO', 'CASSITERITA', 'ALUVIÃO ESTANÍFERO', 'ESTANHO'],
    'TÂNTALO': ['TANTALITA', 'TANTALITA-COLUMBITA', 'MINÉRIO DE TÂNTALO'],
    'TERRAS RARAS': ['MONAZITA', 'MINÉRIO DE CÉRIO'],
    'ZIRCÔNIO': ['ZIRCONITA', 'ZIRCÃO', 'MINÉRIO DE ZIRCÔNIO', 'ZIRCÔNIO'],
    'CROMO': ['CROMITA', 'MINÉRIO DE CROMO', 'CROMO'],
    'CARVÃO': ['CARVÃO MINERAL', 'ANTRACITO', 'LINHITO', 'TURFA'],
    'FOSFATO': ['FOSFORITA (O)', 'ROCHA FOSFÁTICA', 'APATITA'],
    'ÁGUA MINERAL': [
        'ÁGUA POTÁVEL DE MESA', 'ÁGUA TERMO MINERAL', 'ÁGUAS TERMAIS', 
        'ÁGUA MINERAL CARBOGAS', 'ÁGUAS OLIGOMINERAIS',
        'ÁGUA MINERAL ALC. TER. CALCI.', 'ÁGUA MINERAL RAD. FON',
        'ÁGUA MINERAL ALC. BIC'
    ],
    'MAGNÉSIO': ['MAGNESITA', 'MINÉRIO DE MAGNÉSIO'],
    'CALCÁRIO': [
        'CALCÁRIO CONCHÍFERO', 'CALCÁRIO DOLOMÍTICO', 'CALCÁRIO CORALÍNEO',
        'CALCÁRIO CALCÍTICO', 'CALCÁRIO INDUSTRIAL', 'CONCHAS CALCÁRIAS',
        'CALCÁRIO MAGNESIANO', 'CALCÁRIO P/ BRITA', 'PEDRA CALCÁRIA'
    ],
    'ARGILA': [
        'ARGILA REFRATÁRIA', 'ARGILA BENTONÍTICA', 'ARGILA CAULÍNICA',
        'ARGILA ALUMINOSA', 'ARGILA VERMELHA', 'ARGILA BRANCA',
        'ARGILA P/CER. VERMELH', 'ARGILA COMUM', 'ARGILA FERRUGINOSA'
    ],
    'AREIA': [
        'AREIA DE FUNDIÇÃO', 'AREIA P/ VIDRO', 'AREIA QUARTZOSA',
        'AREIA INDUSTRIAL', 'AREIA IN NATURA', 'AREIA ALUVIONAR',
        'AREIA FLUVIAL', 'AREIA COMUM', 'AREIA LAVADA'
    ],
    'GRANITO': [
        'GRANITO ORNAMENTAL', 'GRANITO P/ BRITA', 'GRANITO GNÁISSICO',
        'GRANITO P/ REVESTIMENTO', 'BRITA DE GRANITO'
    ],
    'MÁRMORE': ['MÁRMORE DOLOMÍTICO', 'MÁRMORE P/ REVESTIMENTO'],
    'XISTO': ['XISTO ARGILOSO', 'FOLHELHO ARGILOSO', 'FOLHELHO BETUMINOSO'],
    'DIAMANTE': ['DIAMANTE INDUSTRIAL'],
    'TUNGSTÊNIO': ['MINÉRIO DE TUNGSTÊNIO', 'WOLFRAMITA'],
    'ROCHA BETUMINOSA': ['FOLHELHO PIROBETUMINO', 'ROCHA PIROBETUMINOSA'],
    'MINÉRIO DE PLATINA': ['PLATINA'],
    'MINÉRIO DE PRATA': ['PRATA'],
    'BASALTO': ['BASALTO P/ BRITA', 'BASALTO P/ REVESTIMENTO'],
    'GNAISSE': ['GNAISSE P/ BRITA', 'GNAISSE ORNAMENTAL', 'GNAISSE INDUSTRIAL'],
    'DIABÁSIO': ['DIABÁSIO P/ BRITA', 'DIABÁSIO P/ REVESTIMENTO'],
    'TERRAS RARAS': ['MINÉRIO DE LÍTIO', 'MINÉRIO DE NIÓBIO', 'MINÉRIO DE TITÂNIO']
}

In [73]:
mapa = {}
for chave, valores in substituicoes.items():
    for item in valores:
        mapa[item] = chave

df_filtrado['SUBS'] = df_filtrado['SUBS'].replace(mapa)

In [74]:
len(df_filtrado['SUBS'].unique())

221

In [75]:
df_filtrado['SUBS'].unique()

array(['MANGANÊS', 'ÁGUA MINERAL', 'FERRO', 'MÁRMORE', 'CAULIM', 'CARVÃO',
       'ZIRCÔNIO', 'MAGNÉSIO', 'AREIA', 'CALCÁRIO', 'ARGILA', 'AMETISTA',
       'QUARTZO', 'CASCALHO', 'SAIBRO', 'ALUMÍNIO', 'TOPÁZIO', 'PIRITA',
       'COBRE', 'TALCO', 'QUARTZITO', 'ESTANHO', 'PEDRA CORADA', 'FILITO',
       'AGALMATOLITO', 'DIAMANTE', 'FELDSPATO', 'GRAFITA', 'OURO',
       'DOLOMITO', 'CHUMBO', 'FOSFATO', 'FLUORITA', 'BISMUTO',
       'TURMALINA', 'ÁGUA MARINHA', 'CROMO', 'COLUMBITA', 'CANGA',
       'ZINCO', 'TERRAS RARAS', 'GRANITO', 'SERPENTINITO', 'BARITA',
       'GIPSITA', 'XISTO', 'DIABÁSIO', 'ILMENITA', 'NÍQUEL', 'FOLHELHO',
       'BASALTO', 'AMIANTO', 'BERILO', 'ESMERALDA', 'TUNGSTÊNIO',
       'CALCITA', 'PIROFILITA', 'DIATOMITO', 'PEDRA ORNAMENTAL',
       'LEUCITA', 'POLUCITA', 'SCHEELITA', 'TITÂNIO', 'ARDÓSIA',
       'AMBLIGONITA', 'PETALITA', 'SÍLEX', 'OLIVINA', 'SIENITO',
       'MIGMATITO', 'GNAISSE', 'ARENITO', 'RIÓLITO', 'ROCHA BETUMINOSA',
       'MOLIBDÊNIO', 'VERMICULITA', 'ARENITO BETUMINOSO', 'ESPODUMÊNIO',
       'SAPROPELITO', 'CÁDMIO', 'DIORITO', 'QUARTZITO FRIÁVEL',
       'LIMONITA', 'LEPIDOLITA', 'RUTILO', 'ROCHA POTÁSSICA', 'CIANITA',
       'SALGEMA', 'ENXOFRE', 'BERÍLIO', 'CHARNOQUITO', 'NIÓBIO',
       'SILVINITA', 'VARVITO', 'LEUCOFILITO', 'BENTONITA',
       'QUARTZO INDUSTRIAL', 'NEFELINA', 'ESTEATITO', 'TRAQUITO',
       'ARGILITO', 'TUFO', 'GEMA', 'ANFIBOLITO', 'ALEXANDRITA', 'SILTITO',
       'SAIS DE SÓDIO', 'GRANULITO', 'MINÉRIO DE PLATINA', 'TÂNTALO',
       'KINZIGITO', 'CAULIM ARGILOSO', 'GRANODIORITO', 'GABRO', 'MICA',
       'PALÁDIO', 'SEIXOS ROLADOS', 'TONALITO', 'MINÉRIO DE PRATA',
       'GIPSO', 'DIORITO P/ BRITA', 'MONZONITO', 'GRANADA',
       'SAIS DE POTÁSSIO', 'SIENITO INDUSTRIAL', 'SÍLICA', 'SEIXOS',
       'ANIDRITA', 'LÍTIO', 'OCRE', 'SODALITA', 'CONGLOMERADO',
       'MINÉRIO DE MERCÚRIO', 'GRANODIORITO INDUSTRIAL',
       'MIGMATITO INDUSTRIAL', 'LATERITA', 'DIOPSÍDIO', 'CARNALITA',
       'MINÉRIO DE SILÍCIO', 'VANÁDIO', 'CRISOBERILO', 'PIROXENITO',
       'MINÉRIO DE BERÍLIO', 'MICAXISTO', 'QUARTZITO INDUSTRIAL', 'OPALA',
       'PEGMATITO', 'PEDREGULHO', 'CASCALHO DIAMANTÍFERO', 'ANDESITO',
       'ARSÊNIO', 'NEFELINA SIENITO', 'MINÉRIO DE VANÁDIO', 'FONÓLITO',
       'DACITO', 'TOPÁZIO IMPERIAL', 'CASCALHO SILICOSO', 'CORÍNDON',
       'METACONGLOMERADO', 'TINGUAÍTO', 'MOLIBDENITA', 'ATAPULGITA',
       'QUARTZITO SERICITICO', 'CALCEDÔNIA', 'MINÉRIO DE MOLIBDÊNIO',
       'ALGAS CALCÁREAS', 'TUFO VULCÂNICO', 'MOSCOVITA',
       'MINÉRIO DE BISMUTO', 'ARCÓSIO', 'TRIPOLITO', 'SAIS DE BROMO',
       'ANFIBÓLIO', 'MINÉRIO DE CÉRIO', 'KUNZITA', 'LATERITA FERRUGINOSA',
       'MONAZITA', 'MINÉRIO DE ARSÊNICO', 'CAULINITA',
       'MINÉRIO DE PALÁDIO', 'CRISTAL DE ROCHA', 'ESTRÔNCIO', 'HÁFNIO',
       'AMAZONITA', 'DIATOMITA', 'BIOTITA GRANITO', 'ANORTOSITO',
       'DUNITO', 'ÁGATA', 'QUARTZITO P/ REVESTIMENTO', 'SODALITA SIENITO',
       'SAFIRA', 'GRANODIORITO P/ REVESTIMENTO', 'MIGMATITO P/ BRITA',
       'SAPONITO', 'CATACLASITO', 'MIGMATITO ORNAMENTAL', 'PIROCLORO',
       'ANTOFILITA', 'MORGANITA', 'NITRATO DE POTÁSSIO',
       'MINÉRIO DE CÁDMIO', 'GNAISSE P/ REVESTIMENTO', 'TITANITA',
       'CITRINO', 'CORDIERITA', 'SAIS DE MAGNÉSIO', 'TURQUESA',
       'MONTMORILONITA', 'RUBI', 'GUANO', 'MINÉRIO DE RUBÍDIO',
       'SIENO GRANITO', 'BORATOS', 'MINÉRIO DE URÂNIO',
       'MINÉRIO DE COBALTO', 'MINÉRIO DE ANTIMÔNIO', 'CRISOPRÁSIO',
       'SIENITO ORNAMENTAL', 'ENDERBITO', 'ANDALUZITA'], dtype=object)

In [76]:
df_filtrado.head()

,WKT,ANO,AREA_HA,NOME,SUBS,USO,UF
0,POINT (-43.7707663707609 -20.6393079010862),1935,161.49,NEXUS MANGANES S.A.,MANGANÊS,Demais substâncias,MG
1,POINT (-46.8417232414918 -20.9479278898186),1935,35.00,Organização Teixeira Mendes Ltda,ÁGUA MINERAL,Demais substâncias,MG
2,POINT (-43.862178918326 -20.4229306108558),1935,38.11,VALE S.A.,FERRO,Demais substâncias,MG
3,POINT (-40.4731400627918 -11.2193638449948),1935,405.00,MINERACAO VALE DO JACURICI S A,MANGANÊS,Demais substâncias,BA
4,POINT (-42.1208439491585 -21.1024869907957),1935,5.43,Empresa Hidromineral Fluminense Ltda-ME,ÁGUA MINERAL,Demais substâncias,RJ

In [ ]:
#categorias = {
 #   "Metais-Ferrosos": ["FERRO", "MINÉRIO DE FERRO", "HEMATITA", "MAGNETITA", "ITABIRITO"],
  #  "Metais-Não-ferrosos": ["ALUMÍNIO", "MINÉRIO DE ALUMÍNIO", "BAUXITA", "COBRE", "NÍQUEL", "ZINCO", "CHUMBO"],
   # "Metais Preciosos": ["OURO", "PRATA", "PALÁDIO", "PLATINA", "MINÉRIO DE OURO", "OURO NATIVO"],
    #"Metais Pesados": ["CROMO", "CÁDMIO", "BISMUTO", "VANÁDIO", "MOLIBDÊNIO", "ESTANHO", "ANTIMÔNIO"],
    #"Terras Rara": ["NIÓBIO", "TÂNTALO", "TERRAS RARAS", "MONAZITA", "RUTILO", "ZIRCÔNIO", "HÁFNIO", "MINÉRIO DE CÉRIO"],
    #"Rochas de Construção/Ornamentais": ["GRANITO", "MÁRMORE", "GNAISSE", "QUARTZITO", "BASALTO", "ARDÓSIA", "MIGMATITO"],
    #"Rochas de Agregados para Brita": ["BRITA DE GRANITO", "SEIXOS", "PEDREGULHO", "CASCALHO", "AREIA", "SAIBRO"],
    #"Minerais Industriais": ["CALCÁRIO", "DOLOMITO", "GIPSITA", "ARGILA", "CAULIM", "FELDSPATO", "TALCO", "SÍLICA", "MICA"],
    #"Químicos / Fertilizantes": ["FOSFATO", "SALGEMA", "ENXOFRE", "SAIS DE POTÁSSIO", "SILVINITA", "ROCHA POTÁSSICA", "CARNALITA"],
    #"Gemas / Minerais Preciosos": ["DIAMANTE", "AMETISTA", "TOPÁZIO", "TURMALINA", "ESMERALDA", "SAFIRA", "RUBI", "OPALA", "CITRINO"],
    #"Hídricos": ["ÁGUA MINERAL", "ÁGUAS TERMAIS", "ÁGUA POTÁVEL DE MESA", "ÁGUA TERMO MINERAL"],
    #"Energéticos": ["CARVÃO MINERAL", "ANTRACITO", "TURFA", "LINHITO", "XISTO BETUMINOSO", "ROCHA BETUMINOSA"]
#}

In [81]:
categorias = {
    "Gemas/Pedras Preciosas": [
        'DIAMANTE', 'ESMERALDA', 'RUBI', 'SAFIRA', 
        'TURMALINA', 'AMETISTA', 'TOPÁZIO', 'ALEXANDRITA', 'ÁGATA',
        'OPALA', 'TURQUESA'
    ],
    
    "Metais Pesados": ['CHUMBO', 'CROMO', 'CÁDMIO', 'ZINCO', 'MERCÚRIO'
    ],

    "Metais Preciosos": ['OURO', 'PRATA', 'PLATINA'
    ],
    
    "Metais Estratégicos": [
        'TUNGSTÊNIO', 'NÍQUEL', 'ALUMÍNIO',
        'FERRO', 'COBRE', 'MANGANÊS', 'TITÂNIO', 'ESTANHO', 'LÍTIO'
    ],
    
    "Minerais Industriais": [
        'QUARTZO', 'FELDSPATO', 'TALCO', 'GRAFITA', 'CAULIM', 'MICA',
        'ENXOFRE', 'GIPSITA', 'BARITA', 'FLUORITA'
    ],
    
    "Rochas de Construção": [
        'GRANITO', 'MÁRMORE', 'BASALTO', 'ARDÓSIA', 'ARENITO',
        'GNAISSE', 'CALCÁRIO'
    ],
    
    "Recursos Energéticos": [
        'CARVÃO', 'URÂNIO'
    ],
    
    "Elementos/Compostos Químicos": [
        'FOSFATO', 'SÍLICA', 'BORATOS', 'MAGNÉSIO'
    ],
    
    "Agregados/Sedimentos": [
        'AREIA', 'ARGILA', 'CASCALHO', 'SAIBRO'
    ],

    "Recursos Hídricos": [
        'ÁGUA MINERAL'
    ],
}

In [82]:
def mapear_categoria(subs):
    for categoria, substancias in categorias.items():
        if subs.upper() in substancias:
            return categoria
    return None

In [83]:
df_filtrado['CATEGORIA'] = df_filtrado['SUBS'].apply(mapear_categoria)

In [84]:
df_filtrado.head()

,WKT,ANO,AREA_HA,NOME,SUBS,USO,UF,CATEGORIA
0,POINT (-43.7707663707609 -20.6393079010862),1935,161.49,NEXUS MANGANES S.A.,MANGANÊS,Demais substâncias,MG,Metais Estratégicos
1,POINT (-46.8417232414918 -20.9479278898186),1935,35.00,Organização Teixeira Mendes Ltda,ÁGUA MINERAL,Demais substâncias,MG,Recursos Hídricos
2,POINT (-43.862178918326 -20.4229306108558),1935,38.11,VALE S.A.,FERRO,Demais substâncias,MG,Metais Estratégicos
3,POINT (-40.4731400627918 -11.2193638449948),1935,405.00,MINERACAO VALE DO JACURICI S A,MANGANÊS,Demais substâncias,BA,Metais Estratégicos
4,POINT (-42.1208439491585 -21.1024869907957),1935,5.43,Empresa Hidromineral Fluminense Ltda-ME,ÁGUA MINERAL,Demais substâncias,RJ,Recursos Hídricos

In [85]:
df_filtrado = df_filtrado[df_filtrado['CATEGORIA'].notna()]

In [86]:
df_filtrado

,WKT,ANO,AREA_HA,NOME,SUBS,USO,UF,CATEGORIA
0,POINT (-43.7707663707609 -20.6393079010862),1935,161.49,NEXUS MANGANES S.A.,MANGANÊS,Demais substâncias,MG,Metais Estratégicos
1,POINT (-46.8417232414918 -20.9479278898186),1935,35.00,Organização Teixeira Mendes Ltda,ÁGUA MINERAL,Demais substâncias,MG,Recursos Hídricos
2,POINT (-43.862178918326 -20.4229306108558),1935,38.11,VALE S.A.,FERRO,Demais substâncias,MG,Metais Estratégicos
3,POINT (-40.4731400627918 -11.2193638449948),1935,405.00,MINERACAO VALE DO JACURICI S A,MANGANÊS,Demais substâncias,BA,Metais Estratégicos
4,POINT (-42.1208439491585 -21.1024869907957),1935,5.43,Empresa Hidromineral Fluminense Ltda-ME,ÁGUA MINERAL,Demais substâncias,RJ,Recursos Hídricos
...,...,...,...,...,...,...,...,...
251211,POINT (-44.0234890166965 -20.058412152867),2007,0.14,"Roihter Minerdora, Logistica e Transportes Ltda",FERRO,Industrial,MG,Metais Estratégicos
251212,POINT (-44.0207167904153 -20.0580311016671),2007,0.79,"Roihter Minerdora, Logistica e Transportes Ltda",FERRO,Industrial,MG,Metais Estratégicos
251213,POINT (-44.0236687863779 -20.0560308672697),2007,0.45,"Roihter Minerdora, Logistica e Transportes Ltda",FERRO,Industrial,MG,Metais Estratégicos
251214,POINT (-44.0302583381572 -20.0626539072468),2007,4.84,"Roihter Minerdora, Logistica e Transportes Ltda",FERRO,Industrial,MG,Metais Estratégicos
251219,POINT (-47.5358940440123 -15.2928348626133),2016,282.36,QUARTZITI MINERADORA LTDA,ARGILA,Industrial,GO,Agregados/Sedimentos

In [87]:
df_ordenado = df_filtrado.sort_values(by='ANO', ascending=False)
df_ordenado

,WKT,ANO,AREA_HA,NOME,SUBS,USO,UF,CATEGORIA
227738,POINT (-63.0736822219999 -9.79290722199994),2025,50.00,"M Z CONSTRUCAO, MINERACAO, INDUSTRIA E COMERCI...",GRANITO,Brita,RO,Rochas de Construção
227300,POINT (-49.0886556944999 -5.38084569449993),2025,48.95,G & L CONSTRUTORA LTDA,CASCALHO,Construção civil,PA,Agregados/Sedimentos
229207,POINT (-49.5518613017392 -15.565175469458),2025,382.37,MINERACAO GALANTA K.U.K. LTDA,GNAISSE,Revestimento,GO,Rochas de Construção
227783,POINT (-52.808519421103 -29.694993381185),2025,0.61,Prefeitura Municipal de Candelária,ARGILA,Construção civil,RS,Agregados/Sedimentos
227301,POINT (-42.3494066073891 -3.6117330084468),2025,1977.29,SOUZA E SILVA MINERACOES LTDA,FERRO,Industrial,PI,Metais Estratégicos
...,...,...,...,...,...,...,...,...
2,POINT (-43.862178918326 -20.4229306108558),1935,38.11,VALE S.A.,FERRO,Demais substâncias,MG,Metais Estratégicos
20,POINT (-46.5643859256708 -21.8072902053468),1935,36.23,CIA. INDUSTRIAL DE MINAS GERAIS LTDA.,ÁGUA MINERAL,Demais substâncias,MG,Recursos Hídricos
3,POINT (-40.4731400627918 -11.2193638449948),1935,405.00,MINERACAO VALE DO JACURICI S A,MANGANÊS,Demais substâncias,BA,Metais Estratégicos
41009,POINT (-34.898494997611 -7.13703160543787),1934,472.00,INTERCEMENT ATIVIDADES IMOBILIARIAS S/A,ARGILA,Demais substâncias,PB,Agregados/Sedimentos
168731,POINT (-47.8550199921727 -22.5688035644328),1934,5.55,Prefeitura da Est. Hidrominerall de Águas de S...,ÁGUA MINERAL,Demais substâncias,SP,Recursos Hídricos

In [88]:
colunas = ['ANO'] + [col for col in df_ordenado.columns if col != 'ANO']
df_ordenado = df_ordenado[colunas]

In [89]:
df_ordenado

,ANO,WKT,AREA_HA,NOME,SUBS,USO,UF,CATEGORIA
227738,2025,POINT (-63.0736822219999 -9.79290722199994),50.00,"M Z CONSTRUCAO, MINERACAO, INDUSTRIA E COMERCI...",GRANITO,Brita,RO,Rochas de Construção
227300,2025,POINT (-49.0886556944999 -5.38084569449993),48.95,G & L CONSTRUTORA LTDA,CASCALHO,Construção civil,PA,Agregados/Sedimentos
229207,2025,POINT (-49.5518613017392 -15.565175469458),382.37,MINERACAO GALANTA K.U.K. LTDA,GNAISSE,Revestimento,GO,Rochas de Construção
227783,2025,POINT (-52.808519421103 -29.694993381185),0.61,Prefeitura Municipal de Candelária,ARGILA,Construção civil,RS,Agregados/Sedimentos
227301,2025,POINT (-42.3494066073891 -3.6117330084468),1977.29,SOUZA E SILVA MINERACOES LTDA,FERRO,Industrial,PI,Metais Estratégicos
...,...,...,...,...,...,...,...,...
2,1935,POINT (-43.862178918326 -20.4229306108558),38.11,VALE S.A.,FERRO,Demais substâncias,MG,Metais Estratégicos
20,1935,POINT (-46.5643859256708 -21.8072902053468),36.23,CIA. INDUSTRIAL DE MINAS GERAIS LTDA.,ÁGUA MINERAL,Demais substâncias,MG,Recursos Hídricos
3,1935,POINT (-40.4731400627918 -11.2193638449948),405.00,MINERACAO VALE DO JACURICI S A,MANGANÊS,Demais substâncias,BA,Metais Estratégicos
41009,1934,POINT (-34.898494997611 -7.13703160543787),472.00,INTERCEMENT ATIVIDADES IMOBILIARIAS S/A,ARGILA,Demais substâncias,PB,Agregados/Sedimentos
168731,1934,POINT (-47.8550199921727 -22.5688035644328),5.55,Prefeitura da Est. Hidrominerall de Águas de S...,ÁGUA MINERAL,Demais substâncias,SP,Recursos Hídricos

In [91]:
df_ordenado.to_csv('df_vdd.csv', index=False)